apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: gcp-pubsub-health
build:
  tagPolicy:
    envTemplate:
      template: 'local'
  artifacts:
  - image: gcp-pubsub-health
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
